name: Release Tag
on:
  push:
    branches:
      - main
jobs:
  build:
    name: create release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: label name extract
        id: extract_l_name
        run: echo "::set-output name=LABEL::$(echo '${{ github.event.pull_request.labels }}')"

      - name: version name extract
        id: extract_v_name
        run: |
          echo "::set-output name=VERSION::$(echo "${{ github.ref_name }}")"

      - name: Auto versioning
        run: bash .github/versioning.sh

      - name: Generate release notes
        id: release_notes
        run: echo "::set-output name=notes::$(bash generate-release-notes.sh)"

      - name: Release 생성
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_v_name.outputs.VERSION }}
          release_name: ${{ steps.extract_v_name.outputs.version }}
          body: ${{ steps.release_notes.outputs.notes }}
          draft: false
          prerelease: false